name: nizecart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.9.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  iconsax: ^0.0.8
  flutter_carousel_slider: ^1.0.8
  flutter_rating_bar: ^4.0.0
  country_picker: ^2.0.16
  fluttertoast: ^8.0.9
  hive_flutter: ^1.1.0
  flutter_facebook_auth: ^4.4.1+1
  # path_provider: ^2.0.10
  shimmer: ^2.0.0
  geolocator: ^8.0.1
  geocoding: ^2.0.4
  flutter_riverpod: ^1.0.4
  local_auth: ^2.1.2
  url_launcher: ^6.1.5
  share_plus: ^4.4.0
  timeago: ^3.2.2
  pdf: ^3.8.3
  persistent_bottom_nav_bar_v2: ^4.2.5
  flutterwave_standard: ^1.0.4
  nigerian_states_and_lga: ^1.0.0
  http: ^0.13.5
  flutter_local_notifications:
  uuid: ^3.0.6
  # paystack_manager: 
  # flutter_paystack:
  #  git:
  #   url: https://github.com/definitelyme/flutter_paystack.git
  #   ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  

  firebase_auth: ^3.1.0
  firebase_storage: ^10.2.16
  firebase_core: ^1.20.0
  cloud_firestore: ^2.5.3
  google_sign_in: ^5.1.0
  firebase_messaging:



  

  google_maps_flutter: ^2.1.12
  permission_handler: ^9.2.0
  image_picker: ^0.8.5+3
  flutter_slidable: ^1.3.0
  cached_network_image: ^2.5.1
  image_cropper: ^2.0.3
  # http: ^0.13.5
  # dio: ^3.0.9


  cupertino_icons: ^1.0.2
  image_picker_for_web: ^2.1.8

dependency_overrides:
  intl: ^0.17.0  
  http_parser: 



dev_dependencies:
  flutter_test:
    sdk: flutter
  
 
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

 
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
